name: Build & Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.read_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: read_version
        run: |
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[", ]//g')
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        shell: bash

      - name: Build Windows x64
        run: bun run build-window
        shell: bash

      - name: Build macOS ARM64
        run: bun run build-darwin-arm64
        shell: bash

    
